#include "stdafx.h"
#include <cstdlib>
#include <iostream>
#include "FuzzySunTraker.h"
#include "FuzzyMT.h"
#include "FuzzyGS.h"
#include "Objeto.h"
#include "TimerCounter.h"
#include <fstream>
#include <sstream>
#include <string>